### ISSUE TITLE
[JOSE] Badges issue

### ISSUE THREAD

**Issue by BenjMy** [cgre-aachen/gemgis_data#13]
xref https://github.com/openjournals/jose-reviews/issues/185

In the README file, I would expect the badges to link with the proper target i.e.:

- conda forge -> to the conda gemgis forge repo
- pypy -> to the pypy gemgis repo
- (Check also license and doc)

**Comment by AlexanderJuestel** [comment]
Hello @BenjMy, 

thanks for opening this issue. Does your issue imply that you would make the `gemgis_data` repo available on Pypi and via conda forge? As this repo only consists of tutorial materials, we have not considered adding a Pypi and conda forge solution yet. 

What is your take on that?

**Comment by BenjMy** [comment]
Hello Alex,
As I'm not sure I made myself clear (sorry for that), I propose this issue be solved after reviewing the opened PR #22 😉
And I agree there is no need to make the gemgis_data repo available on Pypi.

**Comment by AlexanderJuestel** [comment]
Yeah, somehow, one was created but since there is no code in the repo and only data the previous question came up. But then I will continue working without having in mind to publish the gemgis_data repo on PyPi and fix the installation of gemgis with pip in the other issue and continue then with revising the remaining open tasks for me. 

Thanks for the clarification
