### ISSUE TITLE
[JOSE] pypi installation 

### ISSUE THREAD

**Issue by BenjMy** [cgre-aachen/gemgis_data#14]
xref https://github.com/openjournals/jose-reviews/issues/185

The required dependencies should be installed automatically when you install GemGIS using pip.

`pip install gemgis` runs well but led to missing dependencies after importing GemGIS (matplolib, geopandas,...) . 

You would probably need to revise your setup.py to add the necessary requirements.

**Comment by AlexanderJuestel** [comment]
Dear @BenjMy, 

thanks for this issue. There is an installation page on how to install GemGIS: https://gemgis.readthedocs.io/en/latest/getting_started/installation.html 

I will certainly have to revise this one now that major packages have been updated (e.g. Shapely). We decided on having this step-by-step installation to make sure that every package is properly installed rather than installing everything at once and get problematic errors. GemGIS relies on packages that depend in return on GDAL (geopandas and rasterio) or VTK (pyvista) or Theano (gempy), which can be tricky to install within themselves.

What is your take as a reviewer on that? I would like to keep the installation of GemGIS simple if all major dependencies are properly installed correctly. 

Cheers Alex

**Comment by AlexanderJuestel** [comment]
Dear @BenjMy, 

in combination with your issue here, I will have to refactor some of the code of GemGIS as the pygeos package was merged with Shapely recently. This will make it hopefully a little easier to install GemGIS in the future if one dependency is gone.

**Comment by BenjMy** [comment]
Hello Alex, 

Thanks for the details. 

I understand your point and I think everyone experienced with python and pip would understand. But naively if I use `pip install gemgis`, I expect to have all the required dependencies installed... Hope this would be possible with the new version and the shapely integration. 
I keep an eye on the Gemgis repo and will do a final check for the next round of the paper review. 

Thanks.

**Comment by AlexanderJuestel** [comment]
Hey, 

I can certainly try to get all the dependencies installed via pip for the GemGIS repo!

**Comment by AlexanderJuestel** [comment]
Hello @BenjMy, 

after some consideration, I think we should **not** try to install GemGIS entirely via pip. If you look at the installation instructions for geopandas for using pip, no especially new user would want to "compile and install th[e] C dependencies [of the geopandas dependencies] manually". If you have the most important dependencies installed via conda (geopandas, pyvista, rasterio), then the installation of gemgis via pip is a charm. And we have the installation instructions for gemgis which are easy to follow.

![image](https://user-images.githubusercontent.com/45469915/217458546-8b610f6a-7a2f-448f-ad8f-f448a4aa3545.png)

**Comment by BenjMy** [comment]
Hi @AlexanderJuestel ,

Thanks for your effort in trying to dig out some possible solutions. I understand your concern about a full pip installation. As soon as the instructions and steps are super clear then I don't think it is an issue anymore (feel free to close).
Thanks.

**Comment by AlexanderJuestel** [comment]
The instructions were reworked and should be clear now, closing the issue
